language: common-lisp

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    - LISP=clisp
    - LISP=allegro
    - LISP=abcl
    - LISP=ecl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone -b local https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls
  - git clone https://github.com/m2ym/cl-annot ~/lisp/cl-annot

script:
  - if [ "$COVERALLS" ]; then
      cl -l prove -l cl-coveralls
         -e '(or (coveralls:with-coveralls (:exclude "t")
                   (prove:run :quri-test))
                 (uiop:quit -1))'
    else
      cl -l prove -e '(or (prove:run :quri-test) (uiop:quit -1))'
    fi